// Package rowgolden is TEST SUPPORT for the RR band
// (the run-row-unification plan): it snapshots one database row as a
// complete column→value map and compares it to a checked-in golden file.
//
// The point is byte-identity of the `runs` row each producer writes. RR-2
// collapses five hand-rolled INSERT statements into one; the only proof that
// the refactor changed nothing is that every producer's row is identical,
// column for column and NULL for NULL, before and after. A test that scans
// three named columns cannot give that proof — it proves those three.
//
// Goldens are generated by running the tests with ROWGOLDEN_UPDATE=1 and are
// reviewed like code: a golden diff IS a behaviour diff.
//
// Only test files import this package. It is a normal package rather than a
// _test.go file because two packages (scheduler, workflow) need it and Go has
// no cross-package test helper mechanism.
package rowgolden

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// Null is how a SQL NULL renders in a golden. It is distinct from the empty
// string on purpose: several columns (target_host, runner_tag, env_json) carry
// NULL-vs-” semantics that the claim predicate and the History UI read
// differently, and a golden that collapsed them would not catch a writer that
// started emitting ” where its sibling emits NULL.
const Null = "<NULL>"

// Row is one snapshotted row: column name → rendered value.
type Row map[string]string

// Snapshot reads `SELECT * FROM <table> WHERE <where>` (exactly one row) and
// renders every column. Bytes and strings render verbatim; NULL renders as
// Null; everything else through %v.
func Snapshot(t *testing.T, db *sql.DB, table, where string, args ...any) Row {
	t.Helper()
	rows, err := db.Query("SELECT * FROM "+table+" WHERE "+where, args...) //nolint:gosec // table/where are test literals
	if err != nil {
		t.Fatalf("rowgolden: query %s: %v", table, err)
	}
	defer rows.Close()
	cols, err := rows.Columns()
	if err != nil {
		t.Fatalf("rowgolden: columns: %v", err)
	}
	if !rows.Next() {
		t.Fatalf("rowgolden: no %s row matches %q %v", table, where, args)
	}
	vals := make([]any, len(cols))
	ptrs := make([]any, len(cols))
	for i := range vals {
		ptrs[i] = &vals[i]
	}
	if err := rows.Scan(ptrs...); err != nil {
		t.Fatalf("rowgolden: scan: %v", err)
	}
	if rows.Next() {
		t.Fatalf("rowgolden: more than one %s row matches %q %v — the golden would be ambiguous", table, where, args)
	}
	out := make(Row, len(cols))
	for i, c := range cols {
		out[c] = render(vals[i])
	}
	return out
}

func render(v any) string {
	switch x := v.(type) {
	case nil:
		return Null
	case []byte:
		return string(x)
	case string:
		return x
	default:
		return fmt.Sprintf("%v", x)
	}
}

// Normalize replaces the value of each named column with a placeholder — but
// ONLY when the column is non-NULL. NULL stays Null. So a volatile column still
// proves its presence/absence; only its unpredictable content is masked.
//
// Use it for generated ids and wall-clock timestamps. Do not use it to hide a
// column you have not understood: if a value differs between producers and
// you cannot say why, that is a finding, not noise.
func Normalize(r Row, placeholders map[string]string) Row {
	out := make(Row, len(r))
	for k, v := range r {
		if p, ok := placeholders[k]; ok && v != Null {
			out[k] = p
			continue
		}
		out[k] = v
	}
	return out
}

// Render produces the canonical golden text: one `column = value` line per
// column, sorted by column name, so a diff is stable and readable.
func Render(r Row) string {
	keys := make([]string, 0, len(r))
	for k := range r {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		b.WriteString(k)
		b.WriteString(" = ")
		b.WriteString(r[k])
		b.WriteByte('\n')
	}
	return b.String()
}

// Compare renders r and checks it against testdata/<name>.golden relative to
// the test's working directory (the package dir). With ROWGOLDEN_UPDATE=1 it
// writes the golden instead and reports what it wrote, so a regeneration is
// visible in the test output and never silent.
func Compare(t *testing.T, name string, r Row) {
	t.Helper()
	path := filepath.Join("testdata", name+".golden")
	got := Render(r)
	if os.Getenv("ROWGOLDEN_UPDATE") == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			t.Fatalf("rowgolden: mkdir: %v", err)
		}
		if err := os.WriteFile(path, []byte(got), 0o600); err != nil {
			t.Fatalf("rowgolden: write %s: %v", path, err)
		}
		t.Logf("rowgolden: WROTE %s (%d columns)", path, len(r))
		return
	}
	want, err := os.ReadFile(path) //nolint:gosec // test fixture path
	if err != nil {
		t.Fatalf("rowgolden: read %s: %v — generate it with ROWGOLDEN_UPDATE=1", path, err)
	}
	if string(want) == got {
		return
	}
	t.Errorf("rowgolden: %s differs from golden.\n%s", name, diff(string(want), got))
}

// diff is a line-level comparison good enough to point at the column: goldens
// are one line per column, so a changed column is a changed line.
func diff(want, got string) string {
	wl := strings.Split(strings.TrimRight(want, "\n"), "\n")
	gl := strings.Split(strings.TrimRight(got, "\n"), "\n")
	wm := map[string]bool{}
	for _, l := range wl {
		wm[l] = true
	}
	gm := map[string]bool{}
	for _, l := range gl {
		gm[l] = true
	}
	var b strings.Builder
	for _, l := range wl {
		if !gm[l] {
			b.WriteString("- " + l + "\n")
		}
	}
	for _, l := range gl {
		if !wm[l] {
			b.WriteString("+ " + l + "\n")
		}
	}
	return b.String()
}
